name: CI/CD Pipeline

on:
  pull_request:
    branches: [production,dev]
  push:
    branches: [production,dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

#  sonar:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Download build artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: dist
#          path: dist
#      - name: SonarQube Scan
#        uses: sonarsource/sonarqube-scan-action@v5
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quantisenapp:latest

      - name: Save Docker image tag
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}/quantisenapp:latest" > image_tag.txt

      - name: Upload Docker image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image_tag.txt

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Read Docker image tag
        id: image_tag
        run: echo "tag=$(cat image_tag.txt)" >> $GITHUB_OUTPUT

      - name: Cache Terraform state
        uses: actions/cache@v4
        with:
          path: infra/terraform.tfstate
          key: ${{ runner.os }}-terraform-${{ github.ref }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="docker_image=traorecheikh/quantisenapp"
        working-directory: ./infra
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Apply
        run: terraform import azurerm_resource_group.main /subscriptions/efd35740-0bd8-4c81-a598-a653bfec71b2/resourceGroups/quantisen-rg || true && terraform apply -auto-approve tfplan
        working-directory: ./infra
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Save Terraform state
        run: |
          mkdir -p infra
          echo "${{ steps.image_tag.outputs.tag }}" > infra/terraform.tfstate
        working-directory: ./infra